# Generated by Django 5.2 on 2026-04-04 06:00

import django.db.models.deletion
from django.db import migrations, models


def seed_site_pages(apps, schema_editor):
    SitePage = apps.get_model("website", "SitePage")
    seeds = [
        ("home", "Home"),
        ("about", "About"),
        ("contact", "Contact"),
        ("faqs", "FAQs"),
        ("legal", "Legal"),
    ]
    for key, title in seeds:
        SitePage.objects.get_or_create(page_key=key, defaults={"title": title})


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='related_destinations',
            field=models.ManyToManyField(blank=True, help_text='Destinations this article is associated with (shown on those hub pages).', related_name='blog_posts_tagged', to='website.destination'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_posts',
            field=models.ManyToManyField(blank=True, help_text='Other blog posts to surface as related reading.', related_name='linked_from_posts', to='website.blogpost'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_tours',
            field=models.ManyToManyField(blank=True, help_text='Tours (PDPs) to highlight from this post.', related_name='blog_posts_tagged', to='website.tour'),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('source_page', models.CharField(blank=True, help_text='Page key or path the visitor submitted from.', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_interest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='website.destination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('contact', 'Contact'), ('faqs', 'FAQs'), ('legal', 'Legal')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('intro', models.TextField(blank=True, help_text='Short text below the title (plain text).')),
                ('body', models.TextField(blank=True, help_text='Main copy (plain text; line breaks preserved on the site).')),
                ('show_lead_form', models.BooleanField(default=False, help_text='If enabled, the lead capture form appears on this page (in addition to Contact).')),
                ('featured_attractions', models.ManyToManyField(blank=True, related_name='featured_on_pages', to='website.attraction')),
                ('featured_blog_posts', models.ManyToManyField(blank=True, related_name='featured_on_pages', to='website.blogpost')),
                ('featured_destinations', models.ManyToManyField(blank=True, help_text='Pinned destinations with quick links to hub and sub-pages.', related_name='featured_on_pages', to='website.destination')),
                ('featured_things_to_do', models.ManyToManyField(blank=True, related_name='featured_on_pages', to='website.thingtodo')),
                ('featured_tours', models.ManyToManyField(blank=True, related_name='featured_on_pages', to='website.tour')),
            ],
            options={
                'ordering': ['page_key'],
            },
        ),
        migrations.RunPython(seed_site_pages, migrations.RunPython.noop),
    ]
