# Generated by Django 5.2 on 2026-04-04 06:12

import django.db.models.deletion
from django.db import migrations, models


def seed_dynamic_site(apps, schema_editor):
    SiteSettings = apps.get_model("website", "SiteSettings")
    HomePageConfig = apps.get_model("website", "HomePageConfig")
    ExpertBullet = apps.get_model("website", "ExpertBullet")
    HomeIconFeature = apps.get_model("website", "HomeIconFeature")
    Testimonial = apps.get_model("website", "Testimonial")
    GalleryImage = apps.get_model("website", "GalleryImage")
    FooterNavLink = apps.get_model("website", "FooterNavLink")
    FooterTrustBadge = apps.get_model("website", "FooterTrustBadge")
    SocialLink = apps.get_model("website", "SocialLink")
    PressMention = apps.get_model("website", "PressMention")

    hero = "https://images.unsplash.com/photo-1529154036614-a60975f5c760?w=2400&q=85"
    SiteSettings.objects.update_or_create(
        pk=1,
        defaults={
            "site_name": "Traveler",
            "search_placeholder": "Where do you want to go?",
            "header_locale_label": "EN · USD",
            "default_hero_image_url": hero,
            "default_card_image_url": "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=600&q=80",
            "newsletter_subtitle": "Subscribe for tips, new tours, and exclusive offers.",
            "newsletter_fine_print": "No spam — unsubscribe anytime.",
            "footer_payment_line": "Visa · MC · PayPal",
            "press_bar_intro": "As seen in",
            "copyright_holder": "Traveler",
        },
    )

    video_poster = "https://images.unsplash.com/photo-1469854523086-cc02fe5d8804?w=1600&q=80"
    hc, _ = HomePageConfig.objects.update_or_create(
        pk=1,
        defaults={
            "hero_intro_fallback": "Top-rated small-group tours for world-class wonders — skip lines, expert guides, unforgettable moments.",
            "video_subtitle": "See how we craft every experience — from first booking to the last photo.",
            "video_poster_url": video_poster,
            "video_watch_url": "",
            "community_subtitle": "Real travelers, real moments — tag #TravelerTours to be featured.",
            "testimonial_footer_note": "Highly rated on TripAdvisor & Google",
            "promise_section_subtitle": "Quality experiences, transparent pricing, and teams who genuinely love what they do.",
            "expert_body": "Walk with historians, chefs, and storytellers who live in the cities you visit. Ask anything — from hidden alleys to the best gelato stop after the tour.",
            "expert_image_url": "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&q=80",
            "expert_image_alt": "Tour guide with guests",
            "blog_section_subtitle": "Guides, tips, and inspiration from our blog.",
        },
    )

    ExpertBullet.objects.filter(home=hc).delete()
    bullets = [
        "Licensed & vetted local experts",
        "Small groups for real conversation",
        "Audio headsets on busy sites",
    ]
    for i, text in enumerate(bullets):
        ExpertBullet.objects.create(home=hc, text=text, sort_order=i)

    HomeIconFeature.objects.all().delete()
    icon_rows = [
        ("hero_overlay", "bi-star-fill", "", "4.9 average rating", 0),
        ("hero_overlay", "bi-people", "", "Expert local guides", 1),
        ("hero_overlay", "bi-lightning-charge", "", "Skip-the-line access", 2),
        ("sky_strip", "bi-ticket-perforated", "Skip-the-line access", "Spend time exploring, not waiting in queues.", 0),
        ("sky_strip", "bi-person-badge", "Passionate guides", "Historians and storytellers who bring cities to life.", 1),
        ("sky_strip", "bi-shield-check", "Flexible booking", "Easy changes and responsive support when you need it.", 2),
        ("promise", "bi-heart", "Travel with heart", "Curated itineraries that respect local culture and communities.", 0),
        ("promise", "bi-award", "Award-winning hosts", "Guides chosen for expertise, energy, and five-star service.", 1),
        ("promise", "bi-headset", "Support that shows up", "Real humans on chat, email, and phone when plans change.", 2),
    ]
    for section, icon, title, body, so in icon_rows:
        HomeIconFeature.objects.create(
            section=section, icon=icon, title=title, body=body, sort_order=so, is_active=True
        )

    Testimonial.objects.all().delete()
    for i, (q, a) in enumerate(
        [
            (
                "Flawless from booking to the final stop. Our guide made Rome unforgettable.",
                "Sarah M., Chicago",
            ),
            (
                "Skip-the-line was worth every penny. Small group, big memories.",
                "James L., London",
            ),
            (
                "Professional, friendly, and deeply knowledgeable. Already planning our next trip.",
                "Elena R., Madrid",
            ),
        ]
    ):
        Testimonial.objects.create(quote=q, author=a, rating=5, sort_order=i, is_active=True)

    GalleryImage.objects.all().delete()
    g_urls = [
        "https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=400&q=80",
        "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=400&q=80",
        "https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=400&q=80",
        "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=400&q=80",
        "https://images.unsplash.com/photo-1503220317375-aaad61436b1b?w=400&q=80",
        "https://images.unsplash.com/photo-1533105076920-e74f58629564?w=400&q=80",
    ]
    for i, u in enumerate(g_urls):
        GalleryImage.objects.create(image_url=u, alt_text="", sort_order=i, is_active=True)

    FooterNavLink.objects.all().delete()
    for col, label, href, so in [
        ("company", "About us", "/about/", 0),
        ("company", "Contact", "/contact/", 1),
        ("company", "Legal", "/legal/", 2),
        ("help", "FAQs", "/faqs/", 0),
        ("help", "Support", "/contact/", 1),
        ("help", "Destinations", "/destinations/", 2),
    ]:
        FooterNavLink.objects.create(column=col, label=label, href=href, sort_order=so)

    FooterTrustBadge.objects.all().delete()
    for i, lab in enumerate(["ATO", "IATA", "Sustainable"]):
        FooterTrustBadge.objects.create(label=lab, sort_order=i)

    SocialLink.objects.all().delete()
    for i, (net, u) in enumerate(
        [
            ("instagram", "https://www.instagram.com/"),
            ("facebook", "https://www.facebook.com/"),
            ("youtube", "https://www.youtube.com/"),
        ]
    ):
        SocialLink.objects.create(network=net, url=u, sort_order=i)

    PressMention.objects.all().delete()
    for i, name in enumerate(["Forbes", "CNBC", "Travel Weekly"]):
        PressMention.objects.create(name=name, sort_order=i)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_cms_leads_and_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterNavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('company', 'Company'), ('help', 'Help')], max_length=20)),
                ('label', models.CharField(max_length=120)),
                ('href', models.CharField(help_text='Path like /about/ or full URL.', max_length=400)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['column', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FooterTrustBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeIconFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero_overlay', 'Hero (overlay bar)'), ('sky_strip', 'Sky strip (3 columns)'), ('promise', 'Promise (3 columns)')], max_length=20)),
                ('icon', models.CharField(help_text='Bootstrap Icons class, e.g. bi-star-fill (no leading dot).', max_length=80)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['section', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image_url', models.URLField(blank=True, max_length=500)),
                ('hero_kicker', models.CharField(blank=True, default='Experience more', max_length=120)),
                ('hero_intro_fallback', models.TextField(blank=True, help_text='Shown under the title when the Home SitePage intro is empty.')),
                ('hero_cta_primary_label', models.CharField(default='Explore destinations', max_length=80)),
                ('hero_cta_primary_link', models.CharField(default='/destinations/', help_text='Path (e.g. /contact/) or full https URL.', max_length=400)),
                ('hero_cta_secondary_label', models.CharField(default='Plan a trip', max_length=80)),
                ('hero_cta_secondary_link', models.CharField(blank=True, default='/contact/', max_length=400)),
                ('destinations_kicker', models.CharField(default='Signature experiences', max_length=120)),
                ('destinations_title', models.CharField(default='Top destinations', max_length=200)),
                ('destinations_empty_cta_label', models.CharField(default='Browse all destinations', max_length=120)),
                ('destinations_view_all_label', models.CharField(default='View all destinations', max_length=120)),
                ('home_destinations_limit', models.PositiveSmallIntegerField(default=8)),
                ('video_enabled', models.BooleanField(default=True)),
                ('video_title', models.CharField(default='Why choose our tours?', max_length=200)),
                ('video_subtitle', models.CharField(blank=True, max_length=400)),
                ('video_poster_url', models.URLField(blank=True, max_length=500)),
                ('video_watch_url', models.URLField(blank=True, max_length=500)),
                ('community_title', models.CharField(default='Join our global travel community', max_length=200)),
                ('community_subtitle', models.TextField(blank=True)),
                ('community_hashtag', models.CharField(blank=True, default='#TravelerTours', max_length=80)),
                ('community_follow_label', models.CharField(default='Follow us', max_length=80)),
                ('community_follow_url', models.URLField(blank=True, max_length=500)),
                ('testimonial_section_title', models.CharField(default='Thousands of five-star reviews', max_length=200)),
                ('testimonial_footer_note', models.CharField(blank=True, max_length=300)),
                ('promise_section_title', models.CharField(default='The Traveler promise', max_length=200)),
                ('promise_section_subtitle', models.TextField(blank=True)),
                ('expert_title', models.CharField(default='Expert guides, every step', max_length=200)),
                ('expert_body', models.TextField(blank=True)),
                ('expert_image_url', models.URLField(blank=True, max_length=500)),
                ('expert_image_alt', models.CharField(blank=True, max_length=200)),
                ('expert_cta_label', models.CharField(default='Find a tour', max_length=80)),
                ('expert_cta_link', models.CharField(blank=True, default='/destinations/', max_length=400)),
                ('blog_section_title', models.CharField(default='Travel insights', max_length=200)),
                ('blog_section_subtitle', models.CharField(blank=True, max_length=300)),
                ('blog_view_more_label', models.CharField(default='View more', max_length=80)),
                ('blog_cards_limit', models.PositiveSmallIntegerField(default=4)),
            ],
            options={
                'verbose_name_plural': 'Home page config',
            },
        ),
        migrations.CreateModel(
            name='PressMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Traveler', max_length=120)),
                ('search_placeholder', models.CharField(default='Where do you want to go?', max_length=160)),
                ('header_account_url', models.URLField(blank=True, max_length=500)),
                ('header_cart_url', models.URLField(blank=True, max_length=500)),
                ('header_locale_label', models.CharField(blank=True, default='EN · USD', max_length=80)),
                ('default_hero_image_url', models.URLField(blank=True, help_text='Used when the home hero URL is empty.', max_length=500)),
                ('default_card_image_url', models.URLField(blank=True, help_text='Fallback for blog/destination cards without an image.', max_length=500)),
                ('newsletter_title', models.CharField(default='Get travel inspiration', max_length=200)),
                ('newsletter_subtitle', models.CharField(blank=True, max_length=300)),
                ('newsletter_fine_print', models.CharField(blank=True, max_length=300)),
                ('footer_payment_line', models.CharField(blank=True, max_length=200)),
                ('press_bar_intro', models.CharField(blank=True, default='As seen in', max_length=120)),
                ('copyright_holder', models.CharField(blank=True, default='Traveler', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'X / Twitter'), ('tiktok', 'TikTok')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='listing_image_url',
            field=models.URLField(blank=True, help_text='Thumbnail for blog listings (home, index). Falls back to site default if empty.', max_length=500),
        ),
        migrations.AddField(
            model_name='destination',
            name='homepage_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first among homepage destinations.'),
        ),
        migrations.AddField(
            model_name='destination',
            name='listing_image_url',
            field=models.URLField(blank=True, help_text='Optional image for destination cards on the home page.', max_length=500),
        ),
        migrations.AddField(
            model_name='destination',
            name='show_on_homepage',
            field=models.BooleanField(default=False, help_text='If checked, this destination is prioritized on the home grid (ordered below).'),
        ),
        migrations.CreateModel(
            name='ExpertBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_bullets', to='website.homepageconfig')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_dynamic_site, migrations.RunPython.noop),
    ]
