# Generated by Django 5.2 on 2026-04-04 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_dynamic_site_and_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='body',
            field=models.TextField(blank=True, help_text='Optional longer copy for the attraction detail page.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_attractions',
            field=models.ManyToManyField(blank=True, help_text='Attraction detail pages that should surface this article.', related_name='tagged_blog_posts', to='website.attraction'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_categories',
            field=models.ManyToManyField(blank=True, help_text='Category pages that should surface this article.', related_name='tagged_blog_posts', to='website.destinationcategory'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_things_to_do',
            field=models.ManyToManyField(blank=True, help_text='Things-to-do detail pages that should surface this article.', related_name='tagged_blog_posts', to='website.thingtodo'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='related_attractions',
            field=models.ManyToManyField(blank=True, help_text='Show on matching attraction detail pages.', related_name='tagged_testimonials', to='website.attraction'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='related_categories',
            field=models.ManyToManyField(blank=True, help_text='Show this quote on those category pages (in addition to global rules).', related_name='tagged_testimonials', to='website.destinationcategory'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='related_things_to_do',
            field=models.ManyToManyField(blank=True, help_text='Show on matching things-to-do detail pages.', related_name='tagged_testimonials', to='website.thingtodo'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='related_tours',
            field=models.ManyToManyField(blank=True, help_text='Show on matching tour detail pages.', related_name='tagged_testimonials', to='website.tour'),
        ),
        migrations.AddField(
            model_name='thingtodo',
            name='body',
            field=models.TextField(blank=True, help_text='Optional longer copy for the activity detail page.'),
        ),
        migrations.CreateModel(
            name='AttractionGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='website.attraction')),
            ],
            options={
                'verbose_name': 'attraction gallery image',
                'verbose_name_plural': 'attraction gallery images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategoryGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='website.destinationcategory')),
            ],
            options={
                'verbose_name': 'category gallery image',
                'verbose_name_plural': 'category gallery images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ThingToDoGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('thing_to_do', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='website.thingtodo')),
            ],
            options={
                'verbose_name': 'thing to do gallery image',
                'verbose_name_plural': 'thing to do gallery images',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TourGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='website.tour')),
            ],
            options={
                'verbose_name': 'tour gallery image',
                'verbose_name_plural': 'tour gallery images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
