# Generated by Django 5.2 on 2026-04-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_entity_gallery_blog_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinationcategory',
            name='summary',
            field=models.TextField(blank=True, help_text='Optional short blurb for category cards and hub chips.'),
        ),
        migrations.AddField(
            model_name='tour',
            name='listing_image_url',
            field=models.URLField(blank=True, help_text='Optional thumbnail for tour cards and listings.', max_length=500),
        ),
    ]
