# Generated by Django 5.2 on 2026-04-04 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_user_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    UserProfile = apps.get_model("website", "UserProfile")
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_tour_booking_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='related_tour',
            field=models.ForeignKey(blank=True, help_text='Tour this message refers to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='website.tour'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Set when the visitor was signed in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.cart')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='website.tour')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.CheckConstraint(
                check=models.Q(user__isnull=False) | models.Q(session_key__isnull=False),
                name='website_cart_user_or_session'
            ),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('session_key',), name='website_cart_session_key_uniq_anon'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'tour'), name='website_cartitem_cart_tour_uniq'),
        ),
        migrations.RunPython(backfill_user_profiles, noop_reverse),
    ]
