# Generated by Django 5.2 on 2026-04-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_clear_placeholder_header_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='header_account_url',
            field=models.URLField(blank=True, help_text='Leave blank to use this site’s /account/ (recommended). If set, an extra “External account” link appears in the header only.', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='header_cart_url',
            field=models.URLField(blank=True, help_text='Leave blank to use this site’s /cart/ (recommended). If set, an extra “External cart” link appears in the header only.', max_length=500),
        ),
    ]
