"""
Django settings for traveler project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ys6^xp21q=4b753^o+j)!9cze17=ao0yv5j!pk1=8kohkk8@gi'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'traveler.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'website.context_processors.site_chrome',
                'website.context_processors.account_chrome',
            ],
        },
    },
]

LOGIN_URL = "/account/login/"
LOGIN_REDIRECT_URL = "/account/profile/"
LOGOUT_REDIRECT_URL = "/"

WSGI_APPLICATION = 'traveler.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Sidebar groups for django-jazzmin: hide the flat "Website" app and show models under readable sections.
_JAZZMIN_WEBSITE_MODEL_KEYS = [
    "website.sitesettings",
    "website.homepageconfig",
    "website.homeiconfeature",
    "website.sitepage",
    "website.destination",
    "website.destinationcategory",
    "website.tour",
    "website.attraction",
    "website.thingtodo",
    "website.blogpost",
    "website.testimonial",
    "website.galleryimage",
    "website.lead",
    "website.cart",
    "website.userprofile",
    "website.footernavlink",
    "website.footertrustbadge",
    "website.sociallink",
    "website.pressmention",
]

# django-jazzmin — modern admin skin + dashboard (https://github.com/farridav/django-jazzmin)
JAZZMIN_SETTINGS = {
    "site_title": "Traveler CMS",
    "site_header": "Traveler",
    "site_brand": "Traveler",
    "welcome_sign": "Sign in to manage destinations, tours, and content.",
    "copyright": "Traveler CMS",
    "search_model": ["website.BlogPost", "website.Tour", "auth.User"],
    "topmenu_links": [
        {"name": "View site", "url": "/", "new_window": True},
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "show_theme_chooser": True,
    "related_modal_active": True,
    # App / section order in the sidebar (custom section names + auth).
    "order_with_respect_to": [
        "Home & site",
        "Destinations & tours",
        "Blog & social proof",
        "Visitors & sales",
        "Footer & press",
        "auth",
    ],
    "hide_models": list(_JAZZMIN_WEBSITE_MODEL_KEYS),
    "custom_links": {
        "Home & site": [
            {"model": "website.sitesettings"},
            {"model": "website.homepageconfig"},
            {"model": "website.homeiconfeature"},
            {"model": "website.sitepage"},
        ],
        "Destinations & tours": [
            {"model": "website.destination"},
            {"model": "website.destinationcategory"},
            {"model": "website.tour"},
            {"model": "website.attraction"},
            {"model": "website.thingtodo"},
        ],
        "Blog & social proof": [
            {"model": "website.blogpost"},
            {"model": "website.testimonial"},
            {"model": "website.galleryimage"},
        ],
        "Visitors & sales": [
            {"model": "website.lead"},
            {"model": "website.cart"},
            {"model": "website.userprofile"},
        ],
        "Footer & press": [
            {"model": "website.footernavlink"},
            {"model": "website.footertrustbadge"},
            {"model": "website.sociallink"},
            {"model": "website.pressmention"},
        ],
    },
    "icons": {
        "auth": "fas fa-user-shield",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "Home & site": "fas fa-layer-group",
        "Destinations & tours": "fas fa-map-marked-alt",
        "Blog & social proof": "fas fa-pen-fancy",
        "Visitors & sales": "fas fa-handshake",
        "Footer & press": "fas fa-shoe-prints",
        "website.destination": "fas fa-globe-americas",
        "website.destinationcategory": "fas fa-map-signs",
        "website.tour": "fas fa-route",
        "website.attraction": "fas fa-landmark",
        "website.thingtodo": "fas fa-hiking",
        "website.blogpost": "fas fa-newspaper",
        "website.testimonial": "fas fa-star",
        "website.lead": "fas fa-inbox",
        "website.sitesettings": "fas fa-sliders-h",
        "website.homepageconfig": "fas fa-home",
        "website.homeiconfeature": "fas fa-icons",
        "website.sitepage": "fas fa-file-alt",
        "website.cart": "fas fa-shopping-cart",
        "website.userprofile": "fas fa-id-card",
        "website.galleryimage": "fas fa-images",
        "website.footernavlink": "fas fa-link",
        "website.footertrustbadge": "fas fa-shield-alt",
        "website.sociallink": "fas fa-share-alt",
        "website.pressmention": "fas fa-newspaper",
    },
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-arrow-circle-right",
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light border-bottom",
    "navbar_fixed": True,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "theme": "zephyr",
    "dark_mode_theme": "darkly",
    "default_theme_mode": "light",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
